export * from "./person.dto";
export * from "./user.dto";
export * from "./country.dto";
export * from "./specialty.dto";
export * from "./studyForm.dto";
export * from "./studCard.dto";
export * from "./course.dto";
export * from "./contract.dto";
export * from "./schedule.dto";
export * from "./order.dto";
export * from "./exam.dto";
export * from "./uchplan.dto";
export * from "./marks.dto";
export * from "./debt.dto";
export * from "./document.dto"
export * from "./utils.dto"