import {Course} from "./index";

export interface StudCard {
  id: number;
  person_id: number;
  fis_status_id: number;
  fis_contract_id: number;
  abit_id: number;
  bugh_id: string;
  bank: string;
  account_bank: string;
  god: number;
  nzk: string;
  filenum: string;
  nds_login: string;
  dip_otl: number;
  atdip: number;
  dolj: string;
  foto: null;
  email: string;
  lang: number;
  loc_work: string;
  medal: number;
  n_attest: string;
  n_attest_date: number;
  n_attest_loc: string;
  educ_id: number;
  naprav: number;
  needroom: number;
  phone: string;
  prikaz: string;
  staj: number;
  starosta: 1 | 0 | null;
  aborigen: 1 | 0 | null;
  resident: 1 | 0 | null;
  marred: 1 | 0 | null;
  child: 1 | 0 | null;
  vost: 1 | 0 | null;
  work_on_spec: 1 | 0 | null;
  staj_spec: 0;
  job_gd: 0;
  text1: string;
  out_doc: string;
  fstat_id: number;
  uz_id: number;
  prof_id: string;
  prof_pass: string;
  proforg: 1 | 0 | null;
  parent_id: number;
  stip1c_id: string;
  contr1c_id: number;
  s_phone: string;
  spec_id: number;
  dog_info: null;
  dogdep_id: number;
  uz_type_id: number;
  krsk_id: number;
  up_id: number;
  lks_block: string;
  pass_change: null;
  avg_mark_attestat: number;
  sirota: 1 | 0 | null;
  athlete: 1 | 0 | null;
  dog_c_num: string;
  dog_c_date: string;
  voen_kaf_quiz: 0;
  question: string;
  activeCourse: Course;
}
